### ISSUE TITLE
I have problems submitting.

### ISSUE THREAD

**Issue by klaubel** [learn-co-curriculum/htm-css-code-along-3#11]
i finished Code Along II and submitted it on my terminal, however on learn.co it appears as if i didn't submit it, therefore i don't get the green light to continue with the following exercises properly.
i didn't get a response on my question on learn.co so i decided to skip it and continue with the lessons.
again i started working on Code Along Exercise 3 and the same thing happened. i did everything like in the video and when i submitted nothing changes on learn.co.
is there a problem with learn.co????
why is this happening ??

**Comment by AnnJohn** [comment]
hi @klaubel this looks like a technical problem (we use this space here for issues related specifically to the curriculum content). You can file a bug report (if you hover over your profile in Learn, you'll see a menu with an option to do that) or email support@learn.co

Thanks
