### ISSUE TITLE
Lab not showing that I opened a pull request

### ISSUE THREAD

**Issue by m00se333** [learn-co-curriculum/htm-css-code-along-3#7]
I no longer see where I can report a bug with this update to Learn.co, so this is where I'll file the grievance. Here's the issue I've forked this lab and I am not getting credit for it. Check it out: 
<img width="553" alt="screen shot 2015-12-27 at 2 41 46 pm" src="https://cloud.githubusercontent.com/assets/14082893/12012430/fb349568-aca7-11e5-826a-7a39b07a5078.png">
<img width="286" alt="screen shot 2015-12-27 at 2 38 19 pm" src="https://cloud.githubusercontent.com/assets/14082893/12012419/a29415c8-aca7-11e5-9ebe-9346e45e907d.png">
<img width="1075" alt="screen shot 2015-12-27 at 2 39 01 pm" src="https://cloud.githubusercontent.com/assets/14082893/12012420/a68d12a6-aca7-11e5-8153-9e527fc89bd9.png">

I'd like my green bubble of accomplishment please.

**Comment by AnnJohn** [comment]
If you hover over your profile pic in Learn, you'll see the option to Report a Bug there. Thanks
